### PR TITLE
Simplify jest + babel config

### PR DESCRIPTION
**Pull request by dimadk24**
On the webinar, it seemed it was painful to configure jest + babel to make it work in tests with async/await syntax. Without `regeneratorRuntime is not defined` error.
To my mind, we solved with a bit complex config. With plenty dependencies and config entries.

I thought it shouldn't be so complex and painful, so decided to solve the task with clear and simple config. I did it in [another repo](https://github.com/DimaDK24/test_regenerator_runtime).
Next, I decided to move my config to this original task, so I did it.

You can check if it working and doesn't break anything else easily. Just follow guidelines in [my fork's Readme](https://github.com/DimaDK24/unit-tests-for-youtube-taks-rss-2018q3#readme)

BTW, `npm start` didn't work even before my work. My changes aren't related to it. I suppose it's something wrong with webpack config. I wanted only to fix complex test's config, so left it as it was.

In addition to config changes, I changed Readme to make more clear what is this fork about. I understand, that you can't merge such Readme, but for me, it makes clear what I did it the fork. Do you have any suggestions for this conflict?

### CODE REVIEW

**Comment by davojta** [comment]
It is not working in webpack build. The error is missing regenerator runtime. My variant is still working.

**Comment by dimadk24** [comment]
Oh, thanks, I'll try to fix it

**Comment by dimadk24** [comment]
Now it's working both in webpack and tests.

As far as I get it all, babel convert async/await into some calls to regeneratorRuntime but do not adds it explicitly. Instead, it expects you to load babel polyfill or any other polyfill for regeneratorRuntime.

Babel polyfill implicitly requires regenerator-runtime@0.11.1 (for some reason they want not latest (0.13.1), but 0.11.1), so I just imported it in the top of the index.js and it worked.

**Comment by davojta** [comment]
@DimaDK24 LGTM! I'm merging )

**Pull request merged**
